version: '3.8'

services:
  devapi:
    build: .
    container_name: devapi
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app/app.py